local ignore = {
  dropbar_ignore_patterns = {
    "DressingSelect",
    "TelescopePrompt",
    "Undotree",
    "UndotreeDiff",
    "dashboard",
    "lazy",
    "neo-tree",
    "neogitstatus",
    "qf",
    "toggleterm",
  },

  file_ignore_patterns = {
    "%.7z",
    "%.bz2",
    "%.cache",
    "%.class",
    "%.dll",
    "%.docx",
    "%.dylib",
    "%.epub",
    "%.exe",
    "%.flac",
    "%.ico",
    "%.ipynb",
    "%.jar",
    "%.jpeg",
    "%.jpg",
    "%.lock",
    "%.mkv",
    "%.mp4",
    "%.otf",
    "%.pdb",
    "%.pdf",
    "%.png",
    "%.rar",
    "%.sqlite3",
    "%.svg",
    "%.tar",
    "%.tar.gz",
    "%.ttf",
    "%.webp",
    "%.zip",
    "*.git/*",
    "*/tmp/*",
    ".dart_tool/",
    ".DS_Store",
    ".git/",
    ".github/",
    ".gradle/",
    ".idea/",
    ".settings/",
    ".vale/",
    ".vscode/",
    "__pycache__/*",
    "build/",
    "docs/",
    "env/",
    "gradle/",
    "node_modules/*",
    "target/",
    "thumbs.db",
    "vendor/*",
  },

  lualine_disabled_filetypes = {
    "dashboard",
    -- "neo-tree",
    "toggleterm",
  },

  illuminate_filetypes_denylist = {
    "dashboard",
    "DressingSelect",
    "neo-tree",
    "neogitstatus",
    "lazy",
    "TelescopePrompt",
    "toggleterm",
  },

  undotree_ignore_filetype = {
    "qf",
    "TelescopePrompt",
    "Undotree",
    "UndotreeDiff",
  },

  snippets_exclude = {
    "angular",
    "beancount",
    "blade",
    "cobol",
    "comprehension",
    "csharp",
    "csharpdoc",
    "django",
    "django_rest",
    "djangohtml",
    "dune",
    "edge",
    "fortran",
    "fsh",
    "gdscript",
    "gleam",
    "glsl",
    "haskell",
    "java",
    "javadoc",
    "julia",
    "kdoc",
    "kivy",
    "kotlin",
    "license",
    "loremipsum",
    "mint",
    "next",
    "next-ts",
    "nushell",
    "purescript",
    "pydoc",
    "quarto",
    "react",
    "react-native",
    "react-native-ts",
    "react-ts",
    "reason",
    "relm4",
    "remix-ts",
    "rescript",
    "scala",
    "solidity",
    "systemverilog",
    "tsdoc",
    "twig",
    "unittest",
    "unity",
    "unreal",
    "verilog",
    "vhdl",
    "PowerShell",
  },
}

return ignore
